; Do not use this file directly for deployment.

; This file must be present in the GuiConsole bundle. It defines some frontend connection parameters.

[Server]
; backend ipv4 addr
ipv4="a.b.c.d"
; backend port
port=8080

[Login]
; number of login attempts before the GUI is locked
maxattempt=3

[MonitoringView]
; defined how widgets are grouped in views
; Localisation | Type
layout=Localisation

